id: P009155
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:25:38.609703
source_metadata:
  id: bdr:W1KG22986
  title: ས་མཐོའི་ཕུལ་བྱུང་མི་སྣ།
  author: ''
  volumes:
    88cf32cdaa9c45e39e1a7100ee49e089:
      image_group_id: I1KG23055
      title: ''
      volume_number: 1
      total_pages: 610
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
